/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.appcelerator.ti.admob;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiContext;
import org.appcelerator.titanium.util.TiConfig;

import com.google.ads.AdSize;

@Kroll.module(name="TiAdmob", id="com.appcelerator.ti.admob")
public class TiAdmobModule extends KrollModule
{
	private static final String LCAT = "TiAdmobModule";
	private static final boolean DBG = TiConfig.LOGD;
	
	@Kroll.constant
    public static final int ADSIZE_BANNER = 1;
	@Kroll.constant
    public static final int ADSIZE_IAB_BANNER = 2;
	@Kroll.constant
    public static final int ADSIZE_IAB_LEADERBOARD  = 3;
	@Kroll.constant
    public static final int ADSIZE_IAB_MRECT = 4;

	public TiAdmobModule(TiContext tiContext) {
		super(tiContext);
	}
}
